### ISSUE TITLE
Switching activates an unexpected tab.

### ISSUE THREAD

**Issue by abaljeu** [jsrozner/obsidian-tab-shifter#1]
I have two tab groups, and I press the hotkey to go to the right tab group.  When I do, the tab that was visible there is deactivated and another tab is activated.  When I switch back to the first tab group, the formerly active tab in the right becomes hidden, and some other tab comes to the front on the right side.

**Comment by jsrozner** [comment]
I don't have a clear picture of what is happening. Could you capture take a screencapture (video) and also indicate what keys / mapping you are pressing?

**Comment by jsrozner** [comment]
In the readme, I added a video showing expected behavior; I also added some written explanations of behavior. Please share a video if the plugin is not behaving as I've indicated it should.

**Comment by abaljeu** [comment]
I uninstalled it because it wasn’t usable.  The key doesn’t matter, but let’s say it was Ctrl-T.On the left I have document B.md active.  On the right group I have C.md is visible.  B is in focus.  I press Ctrl-T.  On the right, X.md becomes active and focussed.  I press Ctrl-Shif-T to go back.  On the right C.md becomes visible again..  B regains keyboard focus.Obviously it would be more reasonable if C stayed visible always through this process.On Mar 17, 2024, at 13:34, Josh ***@***.***> wrote:﻿
I don't have a clear picture of what is happening. Could you capture take a screencapture (video) and also indicate what keys / mapping you are pressing?

**Comment by jsrozner** [comment]
Hmm it does sound weird! I have not have any trouble using this plugin and I've been using it for a few weeks. If you shared a video, then I could begin to troubleshoot it. Do you have tabs pinned in side windows? 

In any case it should just be opening the file that was in focus when the command was pressed. I cannot replicate the issue you describe.

I'm on 1.5.8 and most recent is 1.5.9. What version are you on?

**Comment by abaljeu** [comment]
I tried again and I think I was misusing it, or it just happens to work this time.  There is the Move tab to other group command which I didn't realize was a thing, but might have been what I was accidentally using.  Now that I see it, that's very useful.  I've realigned keys and it all seems to work well currently.  I will report back if I see misbehavior again.
Alan ***@***.***
 

    On Sunday, March 17, 2024 at 07:57:51 p.m. EDT, Josh ***@***.***> wrote:  
 
 


Hmm it does sound weird! I have not have any trouble using this plugin and I've been using it for a few weeks. If you shared a video, then I could begin to troubleshoot it. Do you have tabs pinned in side windows?

In any case it should just be opening the file that was in focus when the command was pressed. I cannot replicate the issue you describe.

I'm on 1.5.8 and most recent is 1.5.9. What version are you on?

**Comment by jsrozner** [comment]
Wonderful! I am glad it's useful. Please reopen if you observe any misbehaviors
